version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:rkauzsma@localhost:5432/photo_comment_app
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=photo_gallery_app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

